### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ddaash** [Shaked/docker-whatsapp#3]
The command '/bin/sh -c add-apt-repository ppa:ondrej/php5-5.6' returned a non-zero code: 1

--
Cannot add PPA: 'ppa:~ondrej/ubuntu/php5-5.6'.
The user named '~ondrej' has no PPA named 'ubuntu/php5-5.6'
--

**Comment by c0d3x27** [comment]
i have the same problem can some one please help? im on a mac

**Comment by elalemanyo** [comment]
Same problem here

**Comment by Shaked** [comment]
Basically PHP5.6 is not supported anymore, so I guess the owner of this image has removed it from the hub. 

The reason I am not fixing it, is because the WhatsApp API is no longer being developed and therefore, I don't see any point of continuing supporting this solution. 

If you want, you may create another image with PHP5.6 and just copy paste the rest of the details from the Dockerfile I created.
